### ISSUE TITLE
How export the pt model to onnx?

### ISSUE THREAD

**Issue by chenscottus** [jahongir7174/YOLOv8-human#1]
Hello,

    How can I  export the pt model to onnx?

    I use yolov8 export. But there are a few errors I cannot fix .

    Thanks!

-Scott

**Comment by chenscottus** [comment]
I solved these two issues:
    AttributeError: Can't get attribute 'YOLO' on <module 'nets.nn'
   ModuleNotFoundError: No module named 'utils'

But I got:
    args = {**DEFAULT_CFG_DICT, **ckpt['train_args']}  # combine model and default args, preferring model args

**Comment by jahongir7174** [comment]
Hello,
Thanks for raising an issue.
You can check the [code](https://github.com/jahongir7174/YOLOv8-human/blob/58154f0677e03c8b95ed9894449005e4c72bcb85/utils/util.py#L47) for exporting the model to `onnx` format

**Comment by chenscottus** [comment]
Here is the error when I use you latest code to export to onnx:
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

Thanks!

**Comment by jahongir7174** [comment]
This error happens because of the torch version when you load pre-trained weights.
Please follow the readme file.
