### ISSUE TITLE
Modeling issue

### ISSUE THREAD

**Issue by chenscottus** [jahongir7174/YOLOv8-human#3]
Hello,

    I found out all your models (trained) have 80 coco types and detect all 80 coco objects. I thought it should be only trained on person datasets, include person only.

    Thanks,

-Scott

**Comment by jahongir7174** [comment]
The models are trained on the COCO dataset. Thus, it has 80 classes. You can fine-tune the model based on your dataset

**Comment by chenscottus** [comment]
What is the benefits comparing the yolov8 models from [ultralytics](https://github.com/ultralytics/ultralytics)?

Thanks!

**Comment by jahongir7174** [comment]
the original repo has more features, this repo is mainly designed to understand the original repo easily.
